// <auto-generated by="the Blazor I18n Text compiler" />
namespace SystemSP.I18nText
{
    public partial class TextIndexSoftware : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"License"</summary>
        public string License;

        /// <summary>""</summary>
        public string LicenseApache;

        /// <summary>"Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files, to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so"</summary>
        public string LicenseMit;

        /// <summary>"When your code is free software, you provide the freedom that any user can run your system or program, for any purpose, it can also be studied and improved in some aspects to make it more functional and effective; thus benefiting the apprenticeship community."</summary>
        public string OpenSourceDescription;

        /// <summary>"Open-source software"</summary>
        public string OpenSourceTitle;
    }
}
