// <auto-generated by="the Blazor I18n Text compiler" />
namespace SystemSP.I18nText
{
    public partial class TextIndexSoftware : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"When your code is free software, you provide the freedom that any user can run your system or program, for any purpose, it can also be studied and improved in some aspects to make it more functional and effective; thus benefiting the apprenticeship community."</summary>
        public string OpenSourceDescription;

        /// <summary>"Open-source software"</summary>
        public string OpenSourceTitle;
    }
}
