// <auto-generated by="the Blazor I18n Text compiler" />
namespace SystemSP.I18nText
{
    public partial class TextAdminPage : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Consult the projects and requests hosted on the platform"</summary>
        public string CheckProjects;

        /// <summary>"Statistics of the projects and users of the application"</summary>
        public string CheckStatistics;

        /// <summary>"Check the users registered on the platform"</summary>
        public string CheckUsers;

        /// <summary>"General administrator options"</summary>
        public string Options;

        /// <summary>"Administrator options"</summary>
        public string OptionsAdmin;

        /// <summary>"Projects and requests"</summary>
        public string ProjectAndRequest;

        /// <summary>"published projects"</summary>
        public string PublishedProjects;

        /// <summary>"registered users"</summary>
        public string RegistereUsers;

        /// <summary>"Statistics"</summary>
        public string Statistics;

        /// <summary>"Statistics the views"</summary>
        public string StatisticsVisits;

        /// <summary>"Users"</summary>
        public string UserText;

        /// <summary>"Views"</summary>
        public string visits;
    }
}
