// <auto-generated by="the Blazor I18n Text compiler" />
namespace SystemSP.I18nText
{
    public partial class TextPublicarPage : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Attach the project documentation"</summary>
        public string AddDocuments;

        /// <summary>"Attach the images of the project interface"</summary>
        public string AddImages;

        /// <summary>"Apprentice Last Name"</summary>
        public string ApprenticeLastName;

        /// <summary>"Apprentice Name"</summary>
        public string ApprenticeName;

        /// <summary>"Apprentices information data (Optional)"</summary>
        public string ApprenticesData;

        /// <summary>"Email"</summary>
        public string AprendiceEmail;

        /// <summary>"Add Members"</summary>
        public string BottonAddMembers;

        /// <summary>"Back"</summary>
        public string BottonBack;

        /// <summary>"Continue"</summary>
        public string BottonContinue;

        /// <summary>"Add Member"</summary>
        public string BottonMember;

        /// <summary>"Nombre de la dirección del Sena"</summary>
        public string BrachName;

        /// <summary>"Sena branch name"</summary>
        public string BranchName;

        /// <summary>"Enter a description of the project and its modules, minimum 100 characters"</summary>
        public string CampDescription;

        /// <summary>"Cancel"</summary>
        public string Cancel;

        /// <summary>"Category"</summary>
        public string CategoryForm;

        /// <summary>"Change language"</summary>
        public string ChangedLang;

        /// <summary>"Click here!"</summary>
        public string ClickHere;

        /// <summary>"Confirm password"</summary>
        public string ConfirmPassword;

        /// <summary>"Department"</summary>
        public string Department;

        /// <summary>"Data Base"</summary>
        public string DivDatabase;

        /// <summary>"Email"</summary>
        public string Email;

        /// <summary>"Agriculture and farms"</summary>
        public string FormAgriculture;

        /// <summary>"Art and Design"</summary>
        public string FormArtDesign;

        /// <summary>"Books and libraries"</summary>
        public string FormBookLibrary;

        /// <summary>"Education"</summary>
        public string FormEducation;

        /// <summary>"Entertainment and events"</summary>
        public string FormEntertainmentEvents;

        /// <summary>"Environment"</summary>
        public string FormEnvironment;

        /// <summary>"Finance and jobs"</summary>
        public string FormFinanceJobs;

        /// <summary>"Health &amp; Wellness"</summary>
        public string FormHealthWellness;

        /// <summary>"Real estate and home"</summary>
        public string FormHome;

        /// <summary>"Industry and Commerce"</summary>
        public string FormIndustryCommerce;

        /// <summary>"Music and audio"</summary>
        public string FormMusicAudio;

        /// <summary>"Office automation"</summary>
        public string FormOfficeAutomation;

        /// <summary>"Others"</summary>
        public string FormOthers;

        /// <summary>"Photography"</summary>
        public string FormPhotography;

        /// <summary>"project date"</summary>
        public string FormProject;

        /// <summary>"Supermarket and shops"</summary>
        public string FormShopsMarket;

        /// <summary>"Tools and productivity"</summary>
        public string FormToolsProductivity;

        /// <summary>"Travels and tourism"</summary>
        public string FormTravelsTourism;

        /// <summary>"Vehicles and motorcycles"</summary>
        public string FormVehiclesMotorcycles;

        /// <summary>"Veterinary"</summary>
        public string FormVeterinary;

        /// <summary>"Guide on how to publish"</summary>
        public string Guide1;

        /// <summary>"a project"</summary>
        public string Guide2;

        /// <summary>"Help"</summary>
        public string Help;

        /// <summary>"Project information"</summary>
        public string InfoProject;

        /// <summary>"Interface Images"</summary>
        public string InterfaceImage;

        /// <summary>"Interface Images"</summary>
        public string InterfaceImagesUpdate;

        /// <summary>"Member data (Optional)"</summary>
        public string MemberData;

        /// <summary>"Datos de los integrantes (Opcional)"</summary>
        public string MemberDate;

        /// <summary>"Members"</summary>
        public string MembersUpdate;

        /// <summary>"The password entered &lt;/br&gt; does not match"</summary>
        public string MensajeAlertaPass;

        /// <summary>"Successfully added"</summary>
        public string MessageAddAprendice;

        /// <summary>"An error was generated in the publishing process"</summary>
        public string MessageError;

        /// <summary>"Password was updated successfully"</summary>
        public string MessagePassword;

        /// <summary>"The project has been published successfully"</summary>
        public string MessageSuccess;

        /// <summary>"Name"</summary>
        public string Name;

        /// <summary>"Apprentice Name"</summary>
        public string NameApprentice;

        /// <summary>"Name of the project"</summary>
        public string NameUpdate;

        /// <summary>"New Password"</summary>
        public string NewPassword;

        /// <summary>"News"</summary>
        public string News;

        /// <summary>"About Open Source"</summary>
        public string OpenSource;

        /// <summary>"Option"</summary>
        public string OptionTable;

        /// <summary>"Other"</summary>
        public string OtherType;

        /// <summary>"Cell phone number"</summary>
        public string PhoneNumber;

        /// <summary>"Post Project"</summary>
        public string PostProject;

        /// <summary>"Training project data"</summary>
        public string ProjectDataMessage;

        /// <summary>"Project date"</summary>
        public string ProjectDate;

        /// <summary>"Project description"</summary>
        public string ProjectDescription;

        /// <summary>"Project FIles"</summary>
        public string ProjectFile;

        /// <summary>"Project files"</summary>
        public string ProjectFilesUpdate;

        /// <summary>"Name of the formative project"</summary>
        public string ProjectName;

        /// <summary>"Project Update"</summary>
        public string ProjectUpdate;

        /// <summary>"Publish Project"</summary>
        public string PublishProject;

        /// <summary>"Save"</summary>
        public string Save;

        /// <summary>"Featured and recommended "</summary>
        public string SeeFeatured1;

        /// <summary>"projects"</summary>
        public string SeeFeatured2;

        /// <summary>"See more!"</summary>
        public string SeeMore;

        /// <summary>"Select the technologies used in the development of the training project"</summary>
        public string SelecTechnology;

        /// <summary>"Select File"</summary>
        public string SelectFile;

        /// <summary>"Attach Images"</summary>
        public string SelectImages;

        /// <summary>"Sena headquarters"</summary>
        public string SenaHeadquartes;

        /// <summary>"Technologies used for the Back-End of the application"</summary>
        public string SubTextBack;

        /// <summary>"Technologies used in the application data layer"</summary>
        public string SubTextDatabase;

        /// <summary>"Technologies used for the Front-End of the application"</summary>
        public string SubTextFront;

        /// <summary>"Apprentice Surname"</summary>
        public string SurNameApprentice;

        /// <summary>"Team"</summary>
        public string Team;

        /// <summary>"Team member data"</summary>
        public string TeamMS;

        /// <summary>"Technical"</summary>
        public string Technical;

        /// <summary>"Technologist"</summary>
        public string Technologist;

        /// <summary>"Technology Used"</summary>
        public string TechnologyUsed;

        /// <summary>"Telephone"</summary>
        public string Telephone;

        /// <summary>"Terms of use"</summary>
        public string TermsUse;

        /// <summary>"Project publication date"</summary>
        public string TooltipData;

        /// <summary>"Training city"</summary>
        public string TrainingCity;

        /// <summary>"Training project data"</summary>
        public string TrainingData;

        /// <summary>"Training Type"</summary>
        public string TrainingType;

        /// <summary>"Update your information"</summary>
        public string UpdateInformacion;
    }
}
