// <auto-generated by="the Blazor I18n Text compiler" />
namespace SystemSP.I18nText
{
    public partial class TextNosotros : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Developer"</summary>
        public string cardPerson;

        /// <summary>"Web designer and logic"</summary>
        public string cardPersonThree;

        /// <summary>"Database engineer"</summary>
        public string cardPersonTwo;

        /// <summary>"We welcome you to the best repository on the Sena, you will be part of our great comunity, finding more that 100 projects just one click!"</summary>
        public string textAboutSystem;

        /// <summary>"What are you waiting for to publish your project?"</summary>
        public string textAboutSystempTwo;

        /// <summary>"SystemSp is an information system that was born as a result of an educational project of a Seine headquarters, to be specific in the Financial Services Center (ADSI)."</summary>
        public string textAboutUs;

        /// <summary>"Meet our work team."</summary>
        public string textAboutUsTwo;

        /// <summary>"Generate a community of SENA apprentices, knowing the projects made by themselves, making these systems can be seen and implemented by interested companies."</summary>
        public string textMision;

        /// <summary>"Make apprentices able to publish their projects by helping the new generation of apprentices to have a guide in the learning process."</summary>
        public string textVision;

        /// <summary>"¿About us?"</summary>
        public string tittleAbout;

        /// <summary>"Mission"</summary>
        public string tittleMission;

        /// <summary>"Vision"</summary>
        public string tittleVision;
    }
}
