// <auto-generated by="the Blazor I18n Text compiler" />
namespace SystemSP.I18nText
{
    public partial class TextIndexPage : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Apprentice"</summary>
        public string Apprentice;

        /// <summary>"Company"</summary>
        public string Company;

        /// <summary>"Consult"</summary>
        public string Consult;

        /// <summary>"Create account?"</summary>
        public string CreateAccount;

        /// <summary>"Forgot your password?"</summary>
        public string ForgotPass;

        /// <summary>"Last name"</summary>
        public string LastName;

        /// <summary>"When your code is free software, you provide the freedom that any user can run your system or program, for any purpose, it can also be studied and improved in some aspects to make it more functional and effective; thus benefiting the apprenticeship community."</summary>
        public string licenseText;

        /// <summary>"Free software"</summary>
        public string licenseTitle;

        /// <summary>"License GPL (GNU Public)."</summary>
        public string licenseType;

        /// <summary>"Log-in"</summary>
        public string Login;

        /// <summary>"Mail"</summary>
        public string Mail;

        /// <summary>"Publish your training project and allow Sena, companies and apprentices to visualize your idea. Link with a company and access the monitoring of the implementation of the project."</summary>
        public string MensajeCard1;

        /// <summary>"Contribute to the training of future sena apprentices by allowing other users to access the documentation and code of your project."</summary>
        public string MensajeCard2;

        /// <summary>"Download the documentation and source code of the training projects. And use it according to the licenses granted by the apprentices."</summary>
        public string MensajeCard3;

        /// <summary>"Do you already have an account?"</summary>
        public string MessageAccount;

        /// <summary>"Enter the data to login"</summary>
        public string MessageDataLogin;

        /// <summary>"Enter the data to Register"</summary>
        public string MessageRegister;

        /// <summary>"More information?"</summary>
        public string MoreInformation1;

        /// <summary>"More information on software rights?"</summary>
        public string MoreInformation2;

        /// <summary>"More information on software rights?"</summary>
        public string MoreInformation3;

        /// <summary>"Find the training projects created by the apprentices of Sena. If you are a student, a company or a private individual, can access the software documentation developed by Sena apprentices."</summary>
        public string MsDescription;

        /// <summary>"Welcome to the repository of software projects!"</summary>
        public string MsWelcon;

        /// <summary>"Name"</summary>
        public string Name;

        /// <summary>"Password"</summary>
        public string Password;

        /// <summary>"Popular categories on the platform"</summary>
        public string PopularCategory;

        /// <summary>"Featured and popular projects"</summary>
        public string PopularProyect;

        /// <summary>"Post"</summary>
        public string Post;

        /// <summary>"Popular categories on the platform"</summary>
        public string PupularCategory;

        /// <summary>"Recommended categories to explore"</summary>
        public string RecommendedCategory;

        /// <summary>"Sign-up"</summary>
        public string Registry;

        /// <summary>"Repeat password"</summary>
        public string RepeatPassword;

        /// <summary>"See suggestions"</summary>
        public string SubTittle1;

        /// <summary>"Detail on Free Software"</summary>
        public string SubTittle2;

        /// <summary>"Detail on Free Software"</summary>
        public string SubTittle3;

        /// <summary>"Telephone"</summary>
        public string Telephone;

        /// <summary>"About"</summary>
        public string TextAbout;

        /// <summary>"Bonding"</summary>
        public string TextBonding;

        /// <summary>"Companies"</summary>
        public string TextCompany;

        /// <summary>"Conditions"</summary>
        public string TextConditions;

        /// <summary>"Help"</summary>
        public string TextHelp;

        /// <summary>"Location"</summary>
        public string TextLocation;

        /// <summary>"Projects"</summary>
        public string TextProjects;

        /// <summary>"Requirement"</summary>
        public string TextRequirement;

        /// <summary>"Resources"</summary>
        public string TextResources;

        /// <summary>"Terms"</summary>
        public string TextTerms;

        /// <summary>"Apprentice"</summary>
        public string TittleApprentice;

        /// <summary>"Show your idea"</summary>
        public string TittleCard1;

        /// <summary>"Contribute by publishing your project"</summary>
        public string TittleCard2;

        /// <summary>"Download the documentation and code"</summary>
        public string TittleCard3;

        /// <summary>"Training center"</summary>
        public string TrainingCenter;
    }
}
