// <auto-generated by="the Blazor I18n Text compiler" />
namespace SystemSP.I18nText
{
    public partial class TextViewPage : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Contact information"</summary>
        public string ContactInformation;

        /// <summary>"Download project"</summary>
        public string DownloadProject;

        /// <summary>"Technologies Used in the training project"</summary>
        public string TechnologyMessage;

        /// <summary>"We are the company (X) and we are interested in your great information system (Name of person)."</summary>
        public string TextRequest;

        /// <summary>"See contact"</summary>
        public string TextSeeContact;

        /// <summary>"See description"</summary>
        public string TextSeeDescription;

        /// <summary>"Category"</summary>
        public string TitleCategory;

        /// <summary>"Downloads"</summary>
        public string TitleDownloads;

        /// <summary>"Full list of categories"</summary>
        public string TitleList;

        /// <summary>"Software business"</summary>
        public string TitleRequest;

        /// <summary>"Watch"</summary>
        public string TitleWatch;
    }
}
