// <auto-generated by="the Blazor I18n Text compiler" />
namespace SystemSP.I18nText
{
    public partial class TextCategoriasIndex : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Art and Design"</summary>
        public string Art;

        /// <summary>"Industry and Commerce"</summary>
        public string Commerce;

        /// <summary>"Education"</summary>
        public string Education;

        /// <summary>"Environment"</summary>
        public string Environment;

        /// <summary>"Entertainment and Events"</summary>
        public string Event;

        /// <summary>"Agriculture and Farms"</summary>
        public string Farms;

        /// <summary>"Finance and Jobs"</summary>
        public string Finance;

        /// <summary>"Health and Wellness"</summary>
        public string Health;

        /// <summary>"Estate and Home"</summary>
        public string Home;

        /// <summary>"Books and Libraries"</summary>
        public string Libraries;

        /// <summary>"Vehicles and Motorcycles"</summary>
        public string Motorcycle;

        /// <summary>"Music and Audio"</summary>
        public string Music;

        /// <summary>"Office Complement"</summary>
        public string Office;

        /// <summary>"Other"</summary>
        public string Other;

        /// <summary>"Photography"</summary>
        public string Photography;

        /// <summary>"Supermarkets and Stores"</summary>
        public string Shop;

        /// <summary>"Tools and Productivity"</summary>
        public string Tool;

        /// <summary>"Transport"</summary>
        public string Transport;

        /// <summary>"Travels and tourism"</summary>
        public string Travel;

        /// <summary>"Veterinary"</summary>
        public string Veterinary;
    }
}
